### PR TITLE
Add TPM tests

### PR DESCRIPTION
**Pull request by ohkinozomu**
I created the tests for TPM. If not needed, feel free to close this PR.
Continuous testing is desirable, but it seems that GitHub Actions does not support TPM.

### CODE REVIEW

**Comment by salrashid123** [comment]
thanks for the PR...tests are something i should invest in a lot more here :)


i think you can use the simulator here (i haven't used it before now but worth trying out

```golang
import (
	"testing"

	"github.com/google/go-tpm-tools/simulator"
	"github.com/stretchr/testify/require"
)

func TestTPMPublic(t *testing.T) {

	//tpmDevice, err := tpm2.OpenTPM()
	tpmDevice, err := simulator.Get()

```


---

also, i'm planning on removing the `vault`, `kms` and `pem` signers from this repo and focusing it just on the TPM (since that's probably the main thing people are after).   I'll keep the same package and folder structure but just remove the other 'signers' nobody uses

**Comment by ohkinozomu** [comment]
I was not aware of `github.com/google/go-tpm-tools/simulator`. It's very useful.
I've switched to using the simulator and added GitHub Actions.

**Comment by salrashid123** [comment]
@ohkinozomu  for ref:  i also added test cases to these following sets incase your'e interested in these variation involving tpm and signers or jwt generation

* https://github.com/salrashid123/golang-jwt-tpm
* https://github.com/salrashid123/golang-jwt-pkcs11
* https://github.com/salrashid123/golang-jwt-signer

* https://github.com/salrashid123/go-tpm-wrapping


i also added many more test cases to this repo but for some reason, the push to main doens't trigger the action  incase you have any thoughts (i've never used workflows till this)

https://github.com/salrashid123/signer/blob/master/.github/workflows/test.yaml
https://github.com/salrashid123/signer/actions/workflows/test.yaml


```
$ go test -v
=== RUN   TestTPMPublic
--- PASS: TestTPMPublic (0.04s)
=== RUN   TestTPMSignRSA
--- PASS: TestTPMSignRSA (0.01s)
=== RUN   TestTPMSignRSAFail
--- PASS: TestTPMSignRSAFail (0.02s)
=== RUN   TestTPMSignRSAPSS
--- PASS: TestTPMSignRSAPSS (0.06s)
=== RUN   TestTPMSignECC
--- PASS: TestTPMSignECC (0.00s)
=== RUN   TestTPMSignECCRAW
--- PASS: TestTPMSignECCRAW (0.00s)
=== RUN   TestTPMSignPolicy
--- PASS: TestTPMSignPolicy (0.06s)
=== RUN   TestTPMSignPolicyFail
--- PASS: TestTPMSignPolicyFail (0.01s)
PASS
ok  	github.com/salrashid123/signer/tpm	0.237s

```


-- edit:
  i added a workflow trigger and ran it manually but not on push

**Comment by ohkinozomu** [comment]
@salrashid123 
It was originally my mistake. It will probably be resolved by https://github.com/salrashid123/signer/pull/18.

**Comment by salrashid123** [comment]
thanks; that triggered the workflow on merge

**Pull request merged**
